server:
  port: 8083
  servlet:
    context-path: /deliverformeaapi

logging:
#  file: ./logs/app.log
#  maxhistory: 30
  level:
    root: INFO
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
  path: logs

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5555/deliverformedb
    username: extraordinaryit
    password: extraordinaryit
    databaseName: deliverformedb
    host: localhost
    port: 5555
    ssl:
      enabled: false
    liquibase:
      changelog: classpath:liquibase/databaseChangeLog.xml
      context: local
      liquibase-schema: deliverforme

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: update
        default_schema: deliverforme
        ddl-auto: create

